"""
textstats.py — text measurement shared by 03_audit_citations.py and 04_analyze_and_plot.py.

  * claim_units(): segment an answer into auditable claim units.
      - every markdown bullet is one unit (bold lead-in + its sentences travel together);
      - prose paragraphs are split into sentences;
      - headings, question/context echo lines, disclaimers, sign-offs and questions
        back to the reader are excluded.
  * fkgl(): Flesch-Kincaid Grade Level with a standard vowel-group syllable heuristic.
  * classify_source(): map a URL to an evidence-source category.

Standard library only.
"""

from __future__ import annotations

import re
from urllib.parse import urlparse

PMID_RE = re.compile(r"PMID:?\s*(\d{5,9})")
PMID_LIST_RE = re.compile(r"\[PMID:?[^\]]*\]")
WEB_MARK_RE = re.compile(r"\[(\d{1,2})\]")

BOILERPLATE = (
    "this is for informational purposes only",
    "generated by tables turned",
    "**question:**",
    "question:",
)


def pmids_in(text: str) -> list[str]:
    """All PMIDs cited anywhere in a bracket, including '[PMID: 1, PMID: 2]' and '[PMID: 1, 2]'."""
    out = []
    for block in PMID_LIST_RE.findall(text):
        out += re.findall(r"\d{5,9}", block)
    for m in PMID_RE.findall(text):          # stray un-bracketed mentions
        out.append(m)
    seen, uniq = set(), []
    for p in out:
        if p not in seen:
            seen.add(p)
            uniq.append(p)
    return uniq


def _split_sentences(par: str) -> list[str]:
    # Protect common abbreviations and decimals, then split on sentence-final punctuation.
    protected = re.sub(r"\b(e\.g|i\.e|vs|et al|Dr|approx|U\.S)\.", lambda m: m.group(0).replace(".", "§"), par)
    parts = re.split(r"(?<=[.!?])\s+(?=[\"*(\[]?[A-Z0-9])", protected)
    return [p.replace("§", ".").strip() for p in parts if p.strip()]


def claim_units(markdown: str) -> list[dict]:
    """Return [{'text': str, 'kind': 'bullet'|'sentence', 'section': str}] for auditable claims."""
    units: list[dict] = []
    section = ""
    for raw in markdown.splitlines():
        line = raw.strip()
        if not line or line in ("---", "***"):
            continue
        low = line.lower()
        if line.startswith("#"):
            section = line.lstrip("#").strip()
            continue
        if any(low.startswith(b) or b in low[:60] for b in BOILERPLATE):
            continue
        if re.fullmatch(r"\*\*[^*]+\*\*:?", line):          # bold pseudo-heading like **Safety**
            section = line.strip("*: ")
            continue
        if re.match(r"^([-*•]|\d+\.)\s+", line):
            text = re.sub(r"^([-*•]|\d+\.)\s+", "", line)
            if text and not text.rstrip().endswith("?"):
                units.append({"text": text, "kind": "bullet", "section": section})
            continue
        for s in _split_sentences(line):
            if s.rstrip("*_ ").endswith("?"):
                continue
            if len(re.findall(r"[A-Za-z]+", s)) < 3:
                continue
            units.append({"text": s, "kind": "sentence", "section": section})
    return units


def plain_text(markdown: str) -> str:
    """Strip markdown, citation markers and URLs for readability scoring."""
    t = PMID_LIST_RE.sub("", markdown)
    t = re.sub(r"\[UNWITNESSED[^\]]*\]", "", t)
    t = WEB_MARK_RE.sub("", t)
    t = re.sub(r"https?://\S+", "", t)
    t = re.sub(r"[*_`#>]", "", t)
    kept = []
    for line in t.splitlines():
        low = line.strip().lower()
        if not low or low == "---" or any(low.startswith(b.strip("*")) for b in BOILERPLATE):
            continue
        line = re.sub(r"^\s*([-•]|\d+\.)\s+", "", line)
        # Headings/bullet lead-ins without terminal punctuation still count as sentences.
        if line and line.strip()[-1] not in ".!?:":
            line = line.strip() + "."
        kept.append(line)
    return " ".join(kept)


def syllables(word: str) -> int:
    w = word.lower()
    w = re.sub(r"[^a-z]", "", w)
    if not w:
        return 0
    if len(w) <= 3:
        return 1
    w = re.sub(r"(?:[^laeiouy]es|ed|[^laeiouy]e)$", "", w)
    w = re.sub(r"^y", "", w)
    return max(1, len(re.findall(r"[aeiouy]{1,2}", w)))


def fkgl(markdown: str) -> dict:
    """Flesch-Kincaid Grade Level: 0.39*(words/sentences) + 11.8*(syllables/words) - 15.59."""
    text = plain_text(markdown)
    sents = [s for s in re.split(r"[.!?:]+\s", text) if re.search(r"[A-Za-z]", s)]
    words = re.findall(r"[A-Za-z][A-Za-z'\-]*", text)
    if not words or not sents:
        return {"fkgl": None, "words": 0, "sentences": 0}
    syl = sum(syllables(w) for w in words)
    grade = 0.39 * (len(words) / len(sents)) + 11.8 * (syl / len(words)) - 15.59
    return {"fkgl": round(grade, 2), "words": len(words), "sentences": len(sents),
            "syllables_per_word": round(syl / len(words), 3), "words_per_sentence": round(len(words) / len(sents), 2)}


# ─────────────────────────────────────────────────────────────
#  Source classification
# ─────────────────────────────────────────────────────────────

SOURCE_CLASSES = [
    "Peer-reviewed literature",
    "Government / public health",
    "Professional society",
    "Academic / hospital",
    "Health media & nonprofits",
    "Commercial / retail",
    "News & other",
]

# Entry syntax: "a.b" matches that domain and its subdomains; entries containing "/" match
# host+path; entries ending in "." or without a dot are substrings of the host (brand names).
_LIT = ("pubmed.ncbi.nlm.nih.gov", "ncbi.nlm.nih.gov/pmc", "pmc.ncbi.nlm.nih.gov", "europepmc.org",
        "sciencedirect.com", "jamanetwork.com", "nejm.org", "thelancet.com", "bmj.com", "nature.com",
        "springer.com", "link.springer.com", "wiley.com", "frontiersin.org", "mdpi.com", "cochranelibrary.com",
        "cochrane.org", "plos.org", "academic.oup.com", "tandfonline.com", "sagepub.com", "cell.com",
        "ahajournals.org", "diabetesjournals.org", "acpjournals.org", "karger.com", "biomedcentral.com",
        "cambridge.org", "medrxiv.org", "biorxiv.org", "lww.com", "aafp.org/pubs", "publications.aap.org",
        "jcsm.aasm.org", "doi.org", "annfammed.org", "journals.lww.com")
_GOV = (".gov", "who.int", "nhs.uk", "canada.ca", "europa.eu", "clinicaltrials.gov", "nih.gov", ".gov.au", ".gov.uk")
_SOC = ("healthychildren.org", "aap.org", "aasm.org", "sleepeducation.org", "heart.org", "diabetes.org",
        "acog.org", "eatright.org", "aafp.org", "gastro.org", "idsociety.org", "endocrine.org",
        "obesitymedicine.org", "asmbs.org", "familydoctor.org", "gi.org")
_MEDIA = ("healthline.com", "webmd.com", "verywellhealth.com", "verywellmind.com", "verywellfit.com",
          "medicalnewstoday.com", "everydayhealth.com", "sleepfoundation.org", "childmind.org", "health.com",
          "prevention.com", "menshealth.com", "womenshealthmag.com", "goodrx.com", "drugs.com", "healthgrades.com",
          "examine.com", "kidshealth.org", "parents.com", "whattoexpect.com", "babycenter.com", "self.com",
          "eatingwell.com", "livestrong.com", "hsph.harvard.edu/nutritionsource", "consumerreports.org",
          "sciencedaily.com", "theconversation.com", "poison.org", "medscape.com", "rxlist.com")
_COMM = ("amazon.", "walmart.", "target.com", "cvs.com", "walgreens.com", "gnc.com", "vitacost.com",
         "iherb.com", "thorne.com", "gardenoflife", "culturelle", "florastor", "bragg.com", "goli.com",
         "ozempic.com", "wegovy.com", "novonordisk", "hims.com", "ro.co", "noom.com", "weightwatchers", "ww.com",
         "hollandandbarrett.com", "withinhealth.com", "ubiehealth.com", "shop.", "store.")
_ACAD = (".edu", ".ac.uk", "utoronto.ca", "mcgill.ca", "ubc.ca", "mayoclinic.org", "mayoclinichealthsystem.org",
         "clevelandclinic.org", "hopkinsmedicine.org", "childrenscolorado.org", "childrenshospital.org", "chop.edu",
         "choa.org", "uclahealth.org", "nyulangone.org", "mountsinai.org", "stanfordchildrens.org",
         "nationwidechildrens.org", "texaschildrens.org", "seattlechildrens.org", "rchsd.org", "cedars-sinai.org",
         "houstonmethodist.org", "osfhealthcare.org", "uchealth.org", "ohsu.edu", "intermountainhealthcare.org",
         "hackensackmeridianhealth.org", "ochsner.org", "nebraskamed.com", "unitypoint.org", "bannerhealth.com",
         "sutterhealth.org", "kp.org", "kaiserpermanente.org", "integrishealth.org", "bswhealth.com",
         "providence.org", "atriumhealth.org", "adventhealth.com", "hackensackmeridian.org", "musc.edu")


def _hit(host: str, full: str, entries: tuple) -> bool:
    for e in entries:
        if "/" in e:
            if e in full:
                return True
        elif e.startswith("."):
            if host.endswith(e):
                return True
        elif e.endswith(".") or "." not in e:
            if e in host:
                return True
        elif host == e or host.endswith("." + e):
            return True
    return False


def classify_source(url: str) -> str:
    """Rule-based mapping from URL to one of SOURCE_CLASSES (first match wins, literature first)."""
    u = url.lower()
    parsed = urlparse(u)
    host = parsed.netloc.split(":")[0]
    host = host[4:] if host.startswith("www.") else host
    full = host + parsed.path
    if _hit(host, full, _LIT):
        return "Peer-reviewed literature"
    if _hit(host, full, _COMM):
        return "Commercial / retail"
    if _hit(host, full, _MEDIA):
        return "Health media & nonprofits"
    if _hit(host, full, _SOC):
        return "Professional society"
    if _hit(host, full, _GOV):
        return "Government / public health"
    if host.startswith("sites.") or host.startswith("blogs."):     # personal/course blogs on .edu hosts
        return "News & other"
    if _hit(host, full, _ACAD):
        return "Academic / hospital"
    return "News & other"
